In [1]:
import DATA
import CONFIG
import CNN

Using TensorFlow backend.


In [2]:
data = DATA.Data()

In [3]:
data.load_data()

  0%|          | 0/38089 [00:00<?, ?it/s]

*** Loading components of Button: 38089 ***


  0%|          | 40/8468 [00:00<00:21, 385.64it/s]

*** Loading components of CheckBox: 8468 ***


100%|██████████| 56/56 [00:00<00:00, 328.45it/s]

*** Loading components of Chronometer: 56 ***



  0%|          | 30/14338 [00:00<00:48, 297.72it/s]

*** Loading components of EditText: 14338 ***


100%|██████████| 14338/14338 [00:17<00:00, 831.00it/s] 


*** Loading components of ImageButton: 82689 ***


100%|██████████| 82689/82689 [00:38<00:00, 2169.12it/s]


*** Loading components of ImageView: 257824 ***


  2%|▏         | 27/1772 [00:00<00:06, 268.19it/s]

*** Loading components of ProgressBar: 1772 ***


  1%|          | 35/4941 [00:00<00:15, 322.04it/s]

*** Loading components of RadioButton: 4941 ***


 12%|█▏        | 113/961 [00:00<00:00, 1089.14it/s]

*** Loading components of RatingBar: 961 ***


  1%|▏         | 25/1835 [00:00<00:07, 243.43it/s]

*** Loading components of SeekBar: 1835 ***


 13%|█▎        | 14/110 [00:00<00:00, 119.98it/s]

*** Loading components of Spinner: 110 ***


  0%|          | 2/3231 [00:00<03:40, 14.63it/s]

*** Loading components of Switch: 3231 ***


  1%|          | 21/2716 [00:00<00:13, 206.43it/s]

*** Loading components of ToggleButton: 2716 ***


  6%|▋         | 20/318 [00:00<00:02, 146.40it/s]

*** Loading components of VideoView: 318 ***


100%|██████████| 318/318 [00:04<00:00, 68.90it/s]

417348 Data Loaded


In [6]:
data.generate_training_data()

MemoryError: 

In [ ]:
cnn = CNN.CNN()

In [ ]:
cnn.train(data, 30)

In [8]:
cnn.evaluate(data)

Model Loaded From E:/Mulong/Model/rico_compos/cnn1.h5
[[15205  3774   984    80     1]
 [ 1973 17657   300    17     0]
 [ 1713   338 13738   203     0]
 [  538   206   581  1884     0]
 [    0     0     0     0     0]]

TP:nan 	 FN:0.334 
FP:nan 	 TN:0.800

recall:nan 	 precision:nan 	 accuracy:nan 	 balanced accuracy:nan


D:\git_file\github\doing\Research-ReverselyGeneratingWebCode\code\MODULE\cnn\CNN.py:50: RuntimeWarning: invalid value encountered in longlong_scalars
  TP += matrix[i][i] / np.sum(matrix[i])
D:\git_file\github\doing\Research-ReverselyGeneratingWebCode\code\MODULE\cnn\CNN.py:52: RuntimeWarning: invalid value encountered in longlong_scalars
  FP += (np.sum(matrix[i]) - matrix[i][i]) / np.sum(matrix[i])
