In [1]:
import DATA
import CONFIG
import CNN

Using TensorFlow backend.


In [2]:
data = DATA.Data()

In [3]:
data.load_data()

*** Loading components of Button: 79792 ***


100%|██████████| 79792/79792 [02:52<00:00, 462.20it/s] 


*** Loading components of Icon: 164659 ***


100%|██████████| 100000/100000 [01:36<00:00, 1035.41it/s]


*** Loading components of Image: 197142 ***


  0%|          | 0/16167 [00:00<?, ?it/s]

*** Loading components of Input: 16167 ***


100%|██████████| 16167/16167 [01:30<00:00, 178.23it/s]

295959 Data Loaded


In [4]:
data.generate_training_data()

X_train:236767, Y_train:236767
X_test:59192, Y_test:59192


In [5]:
cnn = CNN.CNN()

In [6]:
cnn.train(data, 30)

Train on 236767 samples, validate on 59192 samples
Epoch 1/30
236767/236767 [==============================] - 113s 477us/step - loss: 0.7895 - acc: 0.6803 - val_loss: 0.6516 - val_acc: 0.7394
Epoch 2/30
236767/236767 [==============================] - 100s 420us/step - loss: 0.6586 - acc: 0.7423 - val_loss: 0.6958 - val_acc: 0.7321
Epoch 3/30
236767/236767 [==============================] - 98s 412us/step - loss: 0.6186 - acc: 0.7590 - val_loss: 0.6043 - val_acc: 0.7627
Epoch 4/30
236767/236767 [==============================] - 94s 396us/step - loss: 0.5941 - acc: 0.7710 - val_loss: 0.6015 - val_acc: 0.7760
Epoch 5/30
236767/236767 [==============================] - 94s 399us/step - loss: 0.5775 - acc: 0.7780 - val_loss: 0.5581 - val_acc: 0.7897
Epoch 6/30
236767/236767 [==============================] - 96s 403us/step - loss: 0.5643 - acc: 0.7843 - val_loss: 0.5706 - val_acc: 0.7861
Epoch 7/30
236767/236767 [==============================] - 101s 427us/step - loss: 0.5565 - acc: 0.7

In [8]:
cnn.evaluate(data)

Model Loaded From E:/Mulong/Model/rico_compos/cnn1.h5
[[15205  3774   984    80     1]
 [ 1973 17657   300    17     0]
 [ 1713   338 13738   203     0]
 [  538   206   581  1884     0]
 [    0     0     0     0     0]]

TP:nan 	 FN:0.334 
FP:nan 	 TN:0.800

recall:nan 	 precision:nan 	 accuracy:nan 	 balanced accuracy:nan


D:\git_file\github\doing\Research-ReverselyGeneratingWebCode\code\MODULE\cnn\CNN.py:50: RuntimeWarning: invalid value encountered in longlong_scalars
  TP += matrix[i][i] / np.sum(matrix[i])
D:\git_file\github\doing\Research-ReverselyGeneratingWebCode\code\MODULE\cnn\CNN.py:52: RuntimeWarning: invalid value encountered in longlong_scalars
  FP += (np.sum(matrix[i]) - matrix[i][i]) / np.sum(matrix[i])
